// Generated by CoffeeScript 1.12.7
(function () {
  var Descriptor,
    LayerInfo,
    SmartObjectLayerData,
    extend = function (child, parent) {
      for (var key in parent) {
        if (hasProp.call(parent, key)) child[key] = parent[key];
      }
      function ctor() {
        this.constructor = child;
      }
      ctor.prototype = parent.prototype;
      child.prototype = new ctor();
      child.__super__ = parent.prototype;
      return child;
    },
    hasProp = {}.hasOwnProperty;

  LayerInfo = require("../layer_info");

  Descriptor = require("../descriptor");

  module.exports = SmartObjectLayerData = (function (superClass) {
    extend(SmartObjectLayerData, superClass);

    function SmartObjectLayerData() {
      return SmartObjectLayerData.__super__.constructor.apply(this, arguments);
    }

    SmartObjectLayerData.shouldParse = function (key) {
      return key === "SoLd";
    };

    SmartObjectLayerData.prototype.parse = function () {
      this.file.seek(8, true);
      return (this.data = new Descriptor(this.file).parse());
    };

    return SmartObjectLayerData;
  })(LayerInfo);
}.call(this));
